---
name: Rename column or rows
description: Renaming multiple column headers or rows
authors:
    - Max Schubach
input: Input file is tsv table with headers.
output: Output file is tsv table with headers.
params:
    columns: in the form of column=replacement. Must be dictionary
    rows: in the form of row=replacement. Must be dictionary
