---
name: Generate AAUPRC, AUROC, f1 and Accuracy scores
description: Generate multiple auc scores
authors:
    - Max Schubach
input: TSV file with predictions and labels
output: output with auc values
params:
    label_column: name of the column with the labels
    prediction_column: name of the column with the predictions
    positive_label: positive label (float)
